# Generated by Django 2.1.3 on 2018-11-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPerformanceIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('country', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('aggregation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sla_app.AggregationType')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sla_app.Operator'),
        ),
    ]
