# Generated by Django 2.1.3 on 2018-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='customer',
            field=models.CharField(default='customer_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='for_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='kpi_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicator',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicator',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
