# Generated by Django 2.1.3 on 2018-12-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0003_operator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='apn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='mcc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='mnc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_network_cause',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_no_response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_nok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_ok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_per_user',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_per_user_nok',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_per_user_ok',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_sucess',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='transactions_user_cause',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='user_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='users_network_causes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='users_no_response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='users_nok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='users_ok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='users_partially_ok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='users_sucess',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='users_user_causes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
