# Generated by Django 2.1.3 on 2018-12-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0004_auto_20181203_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyperformanceindicator',
            old_name='user_count',
            new_name='users_count',
        ),
    ]
