# Generated by Django 2.1.3 on 2018-12-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0005_auto_20181203_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='apn',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='mcc',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='mnc',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_count',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_network_cause',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_no_response',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_nok',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_ok',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_per_user',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_per_user_nok',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_per_user_ok',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_sucess',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='transactions_user_cause',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_count',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_network_causes',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_no_response',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_nok',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_ok',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_partially_ok',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_sucess',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='users_user_causes',
        ),
    ]
