# Generated by Django 2.1.3 on 2018-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0006_auto_20181204_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyperformanceindicator',
            name='customer',
            field=models.CharField(default='Customer B M2M', max_length=50),
        ),
    ]
