# Generated by Django 2.1.3 on 2018-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0007_keyperformanceindicator_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyperformanceindicator',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
