# Generated by Django 2.1.3 on 2018-12-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0008_auto_20181204_1924'),
        ('sla_app', '0002_auto_20181202_1613'),
    ]

    operations = [
    ]
