# Generated by Django 2.1.3 on 2018-12-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla_app', '0009_merge_20181204_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyperformanceindicator',
            name='for_period',
        ),
    ]
